[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/books/*"
  to = "/.netlify/functions/books/:splat"
  status = 200

[[redirects]]
  from = "/api/books"
  to = "/.netlify/functions/books"
  status = 200
